## Laboratory 4

# The Jacobian

Up until now, we've been discussing about the position and orientation of the
robot as described by transformations. However, it is of special interest to
consider the derivatives of the positions, meaning the velocities and
accelerations. This is especially important since robots can be used in
conditions where speed plays an important role: We usually want to perform a task
as fast as possible, while still making it safe for the environment around the
robot. The objective of this exercise is to define a way for calculating the
end-effector velocity as a function of the joint velocities.

### 4.1. Theoretical considerations

Velocity is defined as the first derivative of the position. When discussing the
velocity of a point, we can only have a linear velocity, since a point does not
have any specific orientation. When discussing about objects though, there is a
distinction between linear and angular velocities. The linear velocity shows us
how fast an object translates relative to a fixed frame, while the angular
velocity shows us how fast does one object rotate relative to a fixed frame.

Each of these velocities has three components, one about each of the axes of the
fixed coordinate frame. We denote the linear velocities as $ \dot{x}, \dot{y}$,
and $ \dot{z} $ and the angular velocities as $ \omega_x, \omega_y$, and $ \omega_z $.


If we define a vector containing all the end-effector velocities defined as 

\begin{equation}
\xi = \begin{bmatrix} \dot{x} & \dot{y} & \dot{z} & \omega_x & \omega_y &
    \omega_z \end{bmatrix}^T \text{ (1)}\\
\end{equation}

we can define the relationship between end-effector and joint velocities as:

\begin{equation}
   \xi = J \dot{q} \text{ (2)}
\end{equation}

where $ \dot{q} $ is a vector containing the velocities of the $ n $ robot
joints. For the multiplication to be feasible, $ J $ should be a matrix and it
should have dimensions $ 6 \times n $. This matrix is called the
_Jacobian_ and we can split it in two $ 3 \times n $ submatrices, one
corresponding to the angular and one to the linear velocities.

#### 4.1.1 ANGULAR velocities

Depending on the design of the robot and the types of joints that it has, it
might be able to change its orientation relative to the fixed frame. 

In the videos below you can see how a 2D robot would move to get to a specific rotation of the end-effector (considered as the end of the red link). 


|The movement of the whole robot|The movement of the end-effector |
|--|--|
|<video controls src="artwork/jacobian/angular_velocity_02.mp4" width=400 />|<video controls src="artwork/jacobian/angular_velocity_01.mp4" width=400 />|

The part of the Jacobian matrix that describes the relationship between joint velocities and
the angular velocity of the end effector is symbolised as $ J_{\omega} $ and it
is a $ 3 \times n $ matrix, where $ n $ is the number of joints.

Since prismatic joints do not produce any rotations, their contribution to the
end-effector angular velocity is zero. Therefore, the columns corresponding to
prismatic joints will be zero.

For revolute joints, the contribution of each joint to each of the three angular
velocities is related to the orientation of the joint. If a joint e.g. is
aligned with the X-axis of the fixed frame, then it will naturally contribute
only to the angular velocity of the end-effector around the X-axis, namely the
$ \omega_x $. Therefore, we define the column of the Jacobian corresponding to
revolute joints equal to the orientation of the joint axis.


If we have used the DH convention for calculating the transformation between two
subsequent joints, then we have defined a coordinate frame whose z-axis is
aligned with the joint axis of rotation. Therefore, the orientation of the
revolute joint $ i $ is equal to the last column of the transformation matrix
$ R_o^i $.


Eventually we have:

\begin{equation}
   J_{\omega} = \begin{bmatrix} J_{\omega 1} & J_{\omega 2} & \dots & J_{\omega
      n} \end{bmatrix} \text{(3) } \\ 
\end{equation}
  where:

\begin{equation}
   J_{\omega i} = \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix} \text{ (4)}\\
\end{equation}
  when $ i $ is a prismatic joint, and:

\begin{equation}
   J_{\omega i} = \begin{bmatrix} Z_x \\ Z_y \\ Z_z \end{bmatrix} \text{ (5)}\\
\end{equation}
  when $ i $ is a revolute joint.
  
  
#### 4.1.2. LINEAR velocities

The linear velocity of the end-effector is affected by both the revolute and the
prismatic joints. 

In the videos below you can see how a 2D robot would move to get to a specific translation of the end-effector (considered as the end of the green link). 

|The movement of the whole robot|The movement of the end-effector |
|--|--|
|<video controls src="artwork/jacobian/linear_velocity_01.mp4" width=400 />|<video controls src="artwork/jacobian/linear_velocity_02.mp4" width=400 />|

The prismatic joints contribute to the linear velocity of the
end effector depending on the orientation of the joint, similar to the way that
revolute joints contribute to the angular velocities. If e.g. a prismatic joint
is oriented with the Z-axis of the fixed frame, then the velocity of the joint
results in a velocity of the end-effector along the Z-axis of the fixed frame,
and no velocity in the other two axes.

Therefore, the column of the linear Jacobian corresponding to a prismatic joint
has the form:

\begin{equation}
   J_{u i} = \begin{bmatrix} Z_x \\ Z_y \\ Z_z \end{bmatrix} \text{ (6)}
\end{equation}


However, contrary to the angular velocities, the linear velocity of the
end-effector does not depend only on the prismatic joints. The revolute joints
have a contribution to the linear velocity of the end-effector as well. This is
similar to the way that the wheels of the car, even though they are just
rotating and not translating, they still cause a linear motion of the car.

The contribution of the revolute joints on the linear velocity of the
end-effector are related to the orientation of the joint, but also to the
distance between the joint and the end effector. This is because a revolute
joint does not only change the orientation of the end-effector, but also it's position.

Finally, the linear velocity resulting from an revolute joint is expressed as a
vector, and more specifically as the cross product between the vectors of the
axis of rotation and the vector connecting the joint origin and the
end-effector. Therefore, for revolute joints the linear Jacobian has the form:

\begin{equation}
   J_{u i} = \begin{bmatrix} z_{i} \times (o_{n+1} - o_{i}) \end{bmatrix}
\end{equation}

The cross product is an operation between two 3D vectors that results in a third 3D vector that is perpedicular to the first two

<center>
    <figure class="image">
      <img src="artwork/jacobian/cross_product.png" width=20% />
      <figcaption>Figure 4.1: Cross product between two vectors </figcaption>
    </figure>
</center>

We can visualise this for a 2D robot as in the figure 4.2:

<center>
    <figure class="image">
      <img src="artwork/jacobian/linear_velocity_revolute.png" width=40% />
      <figcaption>Figure 4.2: The contribution of a revolute joint (q1) on the linear velocity of the end-effector. The cross product of the axis of rotation (blue arrow) and the radius of rotation (magenta arrow) produces the linear velocity vector (green arrow) </figcaption>
    </figure>
</center>

We've seen therefore how a revolute or prismatic joint can contribute to the jacobian of the robot and therefore to the end effector's velocity. In the example below, you can vary the initial pose of the joints (q1, q2) of a 2D robot and then see how the end-effector changes its velocity components depending on the selected joint and type.

In [1]:
%matplotlib qt
from ipywidgets import interact, interact_manual, widgets
from lab_functions import velocity

interact_manual(velocity, q1 = (0, 3.14), q2 = (0, 3.14), joint = ['q1', 'q2'], j_type = ['revolute', 'prismatic'])

interactive(children=(FloatSlider(value=1.57, description='q1', max=3.14), FloatSlider(value=1.57, description…

<function lab_functions.velocity(q1, q2, joint, j_type)>

For the same 2DOF robot as in the previous example, we shall see the variation of the velocities, by changing the q1 and q2 angles. The ellipse represents the vectors of the possible end-effector velocities for a specific configuration of the robot.   

In [2]:
%matplotlib qt
from ipywidgets import interact, interact_manual, widgets
from lab_functions import velocity_ell

interact_manual(velocity_ell, q1 = (0, 3.14), q2 = (0, 3.14))

interactive(children=(FloatSlider(value=1.57, description='q1', max=3.14), FloatSlider(value=1.57, description…

<function lab_functions.velocity_ell(q1, q2)>

### 4.2 Inverse velocities

As with the kinematics, it is usually more useful to be able to solve the
inverse velocities problem i.e. to calculate the joint coordinates that will
result in the desired end-effector velocities. This is accomplished by
multiplying from the left with the inverse of the Jacobian both sides of our
principal equation:

\begin{equation}
   \xi = J \dot{q} \equiv J^{-1}\xi = \dot{q} \text{ (8)}
\end{equation}


However, to be able to do this, the Jacobian must be invertible. For a matrix to
be invertible, it must satisfy two conditions:

- It must be square
- Its rank should be equal to its dimension



As we noticed above, the size of the Jacobian is $ 6 \times n $, where n is the
number of joints. Therefore, for the Jacobian to be invertible we need to have
six joints. The second condition is related to the degrees of freedom as the rank
of the Jacobian is equal to the degrees of freedom of the robot. Therefore for the
Jacobian to be invertible, the robot must not only have six joints, but also they
should be arranged in such a configuration so that they result in six degrees of
freedom.
Since the Jacobian depends on the joint coordinates, we can see that for some
set of joint coordinates, the Jacobian might lose rank and become
non-invertible. When this occurs, we say that the robot is in a
_singular_ configuration. This usually happens when two subsequent links get
aligned, and therefore the influence of one of the two joints on the
end-effector position becomes almost zero (see figure 4.3)

<center>
    <figure class="image">
      <img src="artwork/jacobian/jac1.png" width=40% />
      <figcaption>Figure 4.3: A robot in a singular configuration </figcaption>
    </figure>
</center>

#### 4.2.1. The pseudoinverse


Some times, we have robots with more than 6 joints, still resulting in a robot
with six degrees of freedom. We should be able to calculate the inverse
velocities problem since the robot has the dexterity to impose velocities in and
around all axes. However, our Jacobian is $ 6 \times 7 $ and therefore non
invertible.

To go around this problem, we calculate the pseudoinverse of the Jacobian. The
pseudoinverse is a matrix that if multiplied with the original matrix gives the
identity, just like the real inverse. We calculate it using the following
methodology:

\begin{equation}
   (JJ^T)(JJ^T)^{-1}= I \\
   J[J^T(JJ^T)^{-1}]= I \\ 
   JJ^+ = I \\ 
\end{equation}  

where: 
\begin{equation}
   J^+ = J^T(JJ^T)^{-1} 
\end{equation}

### 4.3 Robotic toolbox for python

The robotics toolbox methods to calculate the jacobian of a robot, for specific configurations. As we saw above,
the Jacobian depends on the joint orientations, which depend on the joint angles. Therefore, the Jacobian is not a fixed quantity. In the following examples, we will work with some predefined robot models, namely the __AL5D__ robot.

We can calculate the Jacobian for a specific configuration running the following command: __jacob0(q)__  where q is a list of the joints' angles. Jacobians can also be computed for symbolic joint variables as for forward kinematics.

In [3]:
import roboticstoolbox as rtb
from math import *
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

al5d = rtb.models.DH.AL5D_mdw()
home = [0, 0, 0, 0, 0]
J = al5d.jacob0(home)
print("Jacobian in config home: \n", J)
print("matrix rank in this config: ", np.linalg.matrix_rank(J))

# You can calculate the pseudoinverse of the Jacobian like this
Jpinv = np.linalg.pinv(J)
print("Pseudojacobian in config home: \n", Jpinv)
print("matrix rank in this config: ", np.linalg.matrix_rank(Jpinv))

Jacobian in config home: 
 [[-0.007 -0.151  0.006 -0.000  0.000]
 [-0.193 -0.000 -0.000  0.000  0.000]
 [ 0.000  0.195 -0.194  0.012  0.000]
 [ 0.000  0.000 -0.000 -0.000 -1.000]
 [-0.000 -1.000  1.000 -1.000 -0.000]
 [-1.000  0.000 -0.000  0.000 -0.000]]
matrix rank in this config:  5
Pseudojacobian in config home: 
 [[-0.000 -0.186 -0.000  0.000 -0.000 -0.964]
 [-6.882  0.009 -0.220  0.000 -0.003  0.048]
 [-6.915  0.009 -5.708  0.000 -0.067  0.048]
 [-0.032  0.000 -5.488  0.000 -1.064  0.000]
 [-0.000  0.000 -0.000 -1.000 -0.000 -0.000]]
matrix rank in this config:  5


In [4]:
import roboticstoolbox as rtb
from spatialmath.base import *
import spatialmath.base.symbolic as sym
from sympy import *

# Example of calculating the symbolic Jacobian of a robot using the toolbox
rob = rtb.models.DH.TwoLink(symbolic=True)
q = sym.symbol("q_:2") 
Jsym = rob.jacob0(q)
Js = Matrix(Jsym)
Jsimple = simplify(Js)
pprint(Jsimple)

Jsub = Jsimple.subs({q[0]:0, q[1]:0})
# pprint (from sympy) for pretty printing of the Matrix type variable
pprint(Jsub)

⎡   -a₁⋅sin(q₀) - a₂⋅sin(q₀ + q₁)      -1.0⋅a₂⋅sin(q₀ + q₁)⎤
⎢                                                          ⎥
⎢                 0                             0          ⎥
⎢                                                          ⎥
⎢1.0⋅a₁⋅cos(q₀) + 1.0⋅a₂⋅cos(q₀ + q₁)  1.0⋅a₂⋅cos(q₀ + q₁) ⎥
⎢                                                          ⎥
⎢                 0                             0          ⎥
⎢                                                          ⎥
⎢                -1.0                          -1.0        ⎥
⎢                                                          ⎥
⎣                 0                             0          ⎦
⎡       0           0   ⎤
⎢                       ⎥
⎢       0           0   ⎥
⎢                       ⎥
⎢1.0⋅a₁ + 1.0⋅a₂  1.0⋅a₂⎥
⎢                       ⎥
⎢       0           0   ⎥
⎢                       ⎥
⎢     -1.0         -1.0 ⎥
⎢                       ⎥
⎣       0           0   ⎦


### 5.4. Proposed problems

Considering the robotic manipulator AL5D fig 4.4.
    
   <center>
        <figure>
          <img src="artwork/DGM/al5d.png"  width=40%/>
        </figure>
        <figure>
          <img src="artwork/DH/AL5D_mdw.png"  width=50%/>
          <figcaption>Figure 4.4: AL5D robot and its schematic </figcaption>
        </figure>
        
   </center>
   
    a. Calculate the Jacobian of the AL5D model for the following set of joint coordinates, given the transformation matrices for each link

$ q= \begin{bmatrix} \pi/6 & -\pi/6 & \pi/8 & 0 & 0 \end{bmatrix} $ [rad]

    b. Create the AL5D model from the robotic toolbox
    c. Calculate the Jacobian for the same sets of joint coordinates below using the robotics toolbox.
    d. Compare the results with your Jacobian for the same joint coordinates.
    e. Calculate the resulting end-effector velocities (linear and angular) for this set of joint coordinates and joint velocities equal to:

$ \dot{q} = \begin{bmatrix} 0.1 & 0.14 & 0.1. & 0.02 & 0.1  \end{bmatrix} $ [rad/s]

    f. Calculate the joint velocities that are required for end-effector linear velocity along the Y-axis of 0.2 m/s (and 0 for the rest)

The transformation matrices for the AL5D robot stored in list `R`. The first element represents $R_0^1$, the second $R_0^2$, and the nth element $R_0^n$. You need to update variable `q` for the desired joint coordinates.

In [76]:
import roboticstoolbox as rtb
import spatialmath.base.symbolic as sym
from spatialmath.base import trotx, trotz, transl
from spatialmath import SE3
import numpy as np
import math as m
from sympy import *
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
init_printing(num_columns=500)

al5d = rtb.models.DH.AL5D_mdw()
home = [m.pi/6,-m.pi/6,m.pi/8,0,0]
J = al5d.jacob0(home)


# creating the model of the robot
rob = rtb.models.DH.AL5D_mdw(symbolic=True)

# initialisations
q = sym.symbol("q:5")
pR = sym.symbol("R_0^1:7")
T = np.eye(4)
R = []

# loop for saving and printing the transformation matrices from the base to joint i in variable R
q = np.array(home)

for i in [0,1,2,3,4]:   
    print(pR[i])
    T = T@rob.links[i].A(q[i]).A
    R.append(T)
    pprint(Matrix(R[i]))
    
print(pR[5])
pprint(Matrix(T*rob.tool))

pR1 = np.array(R[0]);
pR2 = np.array(R[1]);
pR3 = np.array(R[2]);
pR4 = np.array(R[3]);
pR5 = np.array(R[4]);

Jn1 = np.cross(pR1[0:3,2],pR5[0:3,3]-pR1[0:3,3]);
Jw1 = pR1[0:3,2];
Jacobian1 = np.concatenate((Jn1.reshape((3, 1)), (Jw1.reshape((3, 1)))), axis=0);

Jn2 = np.cross(pR2[0:3,2],pR5[0:3,3]-pR2[0:3,3]);
Jw2 = pR2[0:3,2];
Jacobian2 = np.concatenate((Jn2.reshape((3, 1)), (Jw2.reshape((3, 1)))), axis=0);

Jn3 = np.cross(pR3[0:3,2],pR5[0:3,3]-pR3[0:3,3]);
Jw3 = pR3[0:3,2];
Jacobian3 = np.concatenate((Jn3.reshape((3, 1)), (Jw3.reshape((3, 1)))), axis=0);

Jn4 = np.cross(pR4[0:3,2],pR5[0:3,3]-pR4[0:3,3]);
Jw4 = pR4[0:3,2];
Jacobian4 = np.concatenate((Jn4.reshape((3, 1)), (Jw4.reshape((3, 1)))), axis=0);

Jn5 = np.cross(pR5[0:3,2],pR5[0:3,3]-pR5[0:3,3]);
Jw5 = pR5[0:3,2];
Jacobian5 = np.concatenate((Jn5.reshape((3, 1)), (Jw5.reshape((3, 1)))), axis=0);

Jacobian = np.hstack((Jacobian1,Jacobian2,Jacobian3,Jacobian4,Jacobian5));
pprint("\n Jacobian from toolbox:");
pprint(Matrix(J));
pprint("\n Jacobian calculated by me:");
pprint(Matrix(Jacobian));

secondQ = np.array([0.1, 0.14, 0.1, 0.02, 0.1]);
zetta = Jacobian@secondQ;
print("\n End effector velocities:\n", zetta);

zetta2 = np.array([0, 0.2, 0, 0, 0]);
Jpinv = np.linalg.pinv(J[0:5,:]);
newQ = Jpinv@zetta2;
print("\n Joint velocities:\n", newQ)

R_0^1
⎡-0.866025403784439         0.5          0       0   ⎤
⎢                                                    ⎥
⎢       0.5          0.866025403784439   0       0   ⎥
⎢                                                    ⎥
⎢        0                   0          -1.0  0.06858⎥
⎢                                                    ⎥
⎣        0                   0           0      1.0  ⎦
R_0^2
⎡0.437430139655675   -0.747432186168629         -0.5         -0.00173205080756888⎤
⎢                                                                                ⎥
⎢-0.252550408881859  0.431530173885449   -0.866025403784439         0.001        ⎥
⎢                                                                                ⎥
⎢0.863060347770897   0.505100817763719           0                 0.06858       ⎥
⎢                                                                                ⎥
⎣        0                   0                   0                   1.0         ⎦
R_0^3
⎡0.5488482709155

In [ ]:
###### PYTHON INDEXING #######
import numpy as np

# x = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9], [10,11,12,13,14]])

# Element indexing is 0-based
print("\n x matrix is \n", x)
print("\n element at line 1, column 3, is ", x[1, 3])

# Note that if one indexes a multidimensional array with fewer indices than dimensions,
# one gets a subdimensional array. For example:
print("\n element 0 of matrix x is \n ",x[0])

# The basic slice syntax is i:j where i is the starting index, j is the stopping index.
# Assume n is the number of elements in the dimension being sliced. 
# Then, if i is not given it defaults to 0 for k > 0 and n - 1 for k < 0 . 

print("\n Line 0, elements from column 3 onwards are \n ",x[0:1,3:])

print("\n Elements from lines 0 to 1, columns 2 to 3 \n", x[0:2,2:4])

###### USEFUL METHODS #######
# Calculating a cross product
x_arr = np.array([[1,2,3]])
y_arr = np.array([[4,5,6]])

c1 = np.cross(x_arr, y_arr)

print("\n c1: \n", c1, "with shape ", c1.shape)

# reshaping
c2 = c1.reshape((3, 1))
print("\n c2 \n", c2, " with shape ", c2.shape)

# transposing
c3 = c1.T

# concatenating vectors
print("\n c3 and c3 concatenated by line \n", np.concatenate((c3, c3), axis=0))
print("\n c3 and c3 concatenated by column \n", np.concatenate((c3, c3), axis=1))

### Extra exercises
    a. Using the cell below, give different velocity arguments in different scenarios and observe the robot's behaviour.
    b. Using the cell at the end, place the robot in a specific configuration (using new pose option) and, using the interact, visually check for each of the axes the possible instantaneous linear and angular velocities (choosing one joint at a time).

In [ ]:
## extra exercise point a  ##
from al5d_control import *
from ipywidgets import interact, fixed

rrob = AL5DControl()
interact(rrob.robot_control, q0=(-90,90), q1=(-90,90), q2=(-90,90), q3=(-90,90), q4=(-90,90), gripper=(-90,90), dq0=(9,90),dq1=(9,90),dq2=(9,90),dq3=(9,90), dq4=(9,90), vel=fixed(True)) 

In [ ]:
## extra exercise point b  ##
from al5d_control import *
from ipywidgets import interact_manual

rrob = AL5DControl()
interact_manual(rrob.inst_AL5D_velocities, q0=(-90,90),q1=(-90,90),q2=(-90,90),q3=(-90,90),q4=(-90,90), joint = ['new pose','q0', 'q1', 'q2', 'q3','q4']) 